name: Check Code Quality and Run Tests

on:
  pull_request:
    branches:
      - master
jobs:
  code_quality_and_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: "x64"
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install dependencies for development
        run: |
          if [ -f requirements-build.txt ]; then pip install -r requirements-build.txt; fi

      - name: Lint with flake8
        run: |
          flake8 --config=.flake8 .

      - name: Lint with Pylint
        run: |
          pylint --rcfile=.pylintrc .

      - name: Test with pytest
        run: |
          python -m coverage run -m pytest
